version: '3'
services:
  api:
    build:
        context: .
        dockerfile: deploy/Dockerfile.api
    volumes:
      - /vds/:/root/.vds
    restart: always
    ports:
        - "8050:8050/udp"
        - "8050:8050/tcp"
